config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resource :session

  get '/login', to: 'sessions#new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    if cookies.signed[:secure_user_id] == "secure#{session[:user_id]}"
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create
    user = User.find_by(login: params[:login])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      cookies.signed[:secure_user_id] = "secure#{user.id}"
      redirect_to root_url
    else
      flash[:notice] = 'Login Failed'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      flash[:notice] = 'Create user successfully'
      redirect_to login_url
    else
      flash[:notice] = 'Create user fail'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :password)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HijackingSessionDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="main">
    <div id="header">
      <div class="message-bar">
	<div class="error">
	  <p><%= flash[:error] %></p>
	</div>
	<div class="notice">
	  <p><%= flash[:notice] %></p>
	</div>
      </div>
    </div>
    <div class="content">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/users/new.html.erb
<h2>Signup</h2>
<%= form_tag signup_url do -%>
  <div class="form-group">
    <label for='login'>Login:</label>
    <%= text_field_tag 'user[login]', nil -%>
  </div>
  <div class="form-group">
    <label for='password'>Passowrd:</label>
    <%= password_field_tag 'user[password]', nil -%>
  </div>
  <div class="form-group">
    <label for='password'>Passowrd Confirmation:</label>
    <%= password_field_tag 'user[password_confirmation]', nil -%>
  </div>
  <%= submit_tag 'Submit', class: 'btn btn-default' %>
<% end %>

<div class='link-reg'>
  <%= link_to 'Login', login_url %>
</div>

app/views/welcome/index.html.erb
<% if current_user %>
<h2>Welcome: <%=current_user.login%> </h2>
<%= link_to 'Logout', logout_url, method: 'delete'%>
<% else %>
<%=link_to 'Please Login', login_url %>
<% end %>